# LING 281 Project

## Data Preprocessing

In [1]:
%%bash

head allquestionnaires_section5-7all.csv
#head allquestionnaires_section9.csv

Comments_Page1,Session_token,Person_ID,Year_of_birth,Location_grew_up,Sex,Lived_with_who_when_growing_up,Comments_page5,z_calc_Button_label_locations_list,z_calc_Count_other_people,kinships::z_calc_Beliau_label,kinships::z_calc_Where_label,kinships::z_calc_With_who_label,other_people::Ethnicity,other_people::Kinship_type,other_people::Language_used_at_home_now,other_people::Language_used_at_home_when_young,other_people::Language_used_at_home_at_workplace,other_people::Language_used_at_home_with_neighbours,other_people::Language_used_at_home_with_partner,other_people::Language_used_at_home_with_relatives,other_people::Last_level_of_education,other_people::Location_grewup,other_people::Location_of_home,other_people::Profession,other_people::Religion,other_people::Year_of_birth,other_peoples_languages_FirstLanguage::Language_name,other_peoples_languages_OtherLanguages::Language_name
,IMQYYL,1.30403E+23,1991,Jawa Barat - Kota Depok,Laki,Orang tua,,Pilih lokasi dari propinsi ini saja,8,bahasa / dialek yang dia gunakan...,tempat kerja,dengan pasangannya,,Ibu,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang dia gunakan...,tempat kerja,dengan pasangannya,,Bapak,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang beliau gunakan...,tempat kerja,dengan pasangannya,,Ibu dari ibu,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang beliau gunakan...,tempat kerja,dengan pasangannya,,Bapak dari ibu,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang beliau gunakan...,tempat kerja,dengan pasangannya,,Ibu dari bapak,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang beliau gunakan...,tempat kerja,dengan pasangannya,,Bapak dari bapak,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang dia gunakan...,tempat kerja,dengan orang tua,,Istri/Suami,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang dia gunakan...,tempat kerja/sekolah,dengan orang tua,,Anak Anda,,,,,,,, , ,,,,,
#26 5Mar UI,XHMQVM,1.30404E+23,1993,Banten - Kota Tangerang,Laki,Orang tua,,Pilih lokasi dari propinsi ini saja,8,bahasa / dialek yang dia gunakan...,tempat kerja,dengan pasangannya,Betawi,Ibu,,,,,,,SMA,DKI Jakarta,Banten - Kota Tangerang,ibu rumah tangga,Islam,1953,Bahasa Betawi,Bahasa Indonesia

In [2]:
import pandas as pd

In [3]:
sections1_7 = pd.read_csv('allquestionnaires_section5-7all.csv', dtype=str)
sections1_7

,Comments_Page1,Session_token,Person_ID,Year_of_birth,Location_grew_up,Sex,Lived_with_who_when_growing_up,Comments_page5,z_calc_Button_label_locations_list,z_calc_Count_other_people,...,other_people::Language_used_at_home_with_partner,other_people::Language_used_at_home_with_relatives,other_people::Last_level_of_education,other_people::Location_grewup,other_people::Location_of_home,other_people::Profession,other_people::Religion,other_people::Year_of_birth,other_peoples_languages_FirstLanguage::Language_name,other_peoples_languages_OtherLanguages::Language_name
0,NaN,IMQYYL,1.30403E+23,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN,Pilih lokasi dari propinsi ini saja,8,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5291,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Jawa,Jawa,NaN,Jawa Timur - Kabupaten Bojonegoro,Jawa Timur - Kabupaten Bojonegoro,Wiraswasta,Islam,NaN,Jawa,NaN
5292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Jawa,Jawa,NaN,Jawa Timur - Kabupaten Lamongan,Jawa Timur - Kabupaten Lamongan,Ibu rumah tangga,Islam,NaN,Jawa,NaN
5293,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Jawa,Jawa,NaN,Jawa Timur - Kabupaten Lamongan,Jawa Timur - Kabupaten Lamongan,Wiraswasta,Islam,NaN,Jawa,NaN
5294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
5295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN

In [4]:
sections1_7.columns

Index(['Comments_Page1', 'Session_token', 'Person_ID', 'Year_of_birth',
       'Location_grew_up', 'Sex', 'Lived_with_who_when_growing_up',
       'Comments_page5', 'z_calc_Button_label_locations_list',
       'z_calc_Count_other_people', 'kinships::z_calc_Beliau_label',
       'kinships::z_calc_Where_label', 'kinships::z_calc_With_who_label',
       'other_people::Ethnicity', 'other_people::Kinship_type',
       'other_people::Language_used_at_home_now',
       'other_people::Language_used_at_home_when_young',
       'other_people::Language_used_at_home_at_workplace',
       'other_people::Language_used_at_home_with_neighbours',
       'other_people::Language_used_at_home_with_partner',
       'other_people::Language_used_at_home_with_relatives',
       'other_people::Last_level_of_education',
       'other_people::Location_grewup', 'other_people::Location_of_home',
       'other_people::Profession', 'other_people::Religion',
       'other_people::Year_of_birth',
       'other_peoples_languages_FirstLanguage::Language_name',
       'other_peoples_languages_OtherLanguages::Language_name'],
      dtype='object')

In [5]:
sections1_7 = sections1_7.drop(columns=[
    'Person_ID',
    'Comments_page5',
    'z_calc_Button_label_locations_list',
    'z_calc_Count_other_people',
    'kinships::z_calc_Beliau_label',
    'kinships::z_calc_Where_label',
    'kinships::z_calc_With_who_label',
])

sections1_7

,Comments_Page1,Session_token,Year_of_birth,Location_grew_up,Sex,Lived_with_who_when_growing_up,other_people::Ethnicity,other_people::Kinship_type,other_people::Language_used_at_home_now,other_people::Language_used_at_home_when_young,...,other_people::Language_used_at_home_with_partner,other_people::Language_used_at_home_with_relatives,other_people::Last_level_of_education,other_people::Location_grewup,other_people::Location_of_home,other_people::Profession,other_people::Religion,other_people::Year_of_birth,other_peoples_languages_FirstLanguage::Language_name,other_peoples_languages_OtherLanguages::Language_name
0,NaN,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN,Ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5291,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Bapak dari ibu,Jawa,Jawa,...,Jawa,Jawa,NaN,Jawa Timur - Kabupaten Bojonegoro,Jawa Timur - Kabupaten Bojonegoro,Wiraswasta,Islam,NaN,Jawa,NaN
5292,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Ibu dari bapak,Jawa,Jawa,...,Jawa,Jawa,NaN,Jawa Timur - Kabupaten Lamongan,Jawa Timur - Kabupaten Lamongan,Ibu rumah tangga,Islam,NaN,Jawa,NaN
5293,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Bapak dari bapak,Jawa,Jawa,...,Jawa,Jawa,NaN,Jawa Timur - Kabupaten Lamongan,Jawa Timur - Kabupaten Lamongan,Wiraswasta,Islam,NaN,Jawa,NaN
5294,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
5295,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN

In [6]:
sections1_7.columns = [
    'survey_location',
    'session',
    'birth_year',
    'home_location',
    'sex',
    'caretaker',
    'relative_ethnicity',
    'relative_type',
    'relative_curr_home_lang',
    'relative_past_home_lang',
    'relative_work_lang',
    'relative_neighbor_lang',
    'relative_partner_lang',
    'relative_family_lang',
    'relative_education',
    'relative_past_home',
    'relative_curr_home',
    'relative_profession',
    'relative_religion',
    'relative_birth_year',
    'relative_first_lang',
    'relative_other_langs'
]

sections1_7.head(20)

,survey_location,session,birth_year,home_location,sex,caretaker,relative_ethnicity,relative_type,relative_curr_home_lang,relative_past_home_lang,...,relative_partner_lang,relative_family_lang,relative_education,relative_past_home,relative_curr_home,relative_profession,relative_religion,relative_birth_year,relative_first_lang,relative_other_langs
0,NaN,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN,Ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
8,#26 5Mar UI,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,Betawi,Ibu,NaN,NaN,...,NaN,NaN,SMA,DKI Jakarta,Banten - Kota Tangerang,ibu rumah tangga,Islam,1953,Bahasa Betawi,Bahasa Indonesia
9,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Bapak,NaN,NaN,...,NaN,NaN,sarjana,Jawa Timur,Banten - Kota Tangerang,pegawai swasta,Islam,1957,Bahasa Jawa,Bahasa Indonesia
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
16,#25 5Mar UI,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,Jawa,Ibu,Bahasa Jawa,Bahasa Jawa,...,Bahasa Jawa,Bahasa Jawa,S1,Daerah Istimewa Yogyakarta - Kota Yogyakarta,Jawa Barat - Kota Bekasi,ibu rumah tangga,Kristen (Katolik),1968,Bahasa Indonesia,Bahasa Jawa
17,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Bapak,Bahasa Jawa,Bahasa Jawa,...,Bahasa Jawa,Bahasa Jawa,S1,Jawa Tengah - Kota Surakarta,Jawa Barat - Kota Bekasi,Manager HRD,Kristen (Katolik),1965,Bahasa Indonesia,Bahasa Jawa
18,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,Daerah Istimewa Yogyakarta - Kota Yogyakarta,observer,Kristen (Katolik),1951,Bahasa Indonesia,Bahasa Jawa
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,Bahasa Jawa,Bahasa Jawa

In [7]:
section9 = pd.read_csv('allquestionnaires_section9.csv', header=None, dtype=str)
section9

,0,1,2,3,4,5,6
0,NaN,IMQYYL,130403120847605844325106,1991,Jawa Barat - Kota Depok,Laki,NaN
1,#26 5Mar UI,XHMQVM,130404075124817369427531,1993,Banten - Kota Tangerang,Laki,lebih dari 24
2,#25 5Mar UI,OQHPQE,130404080557637889778008,1995,Jawa Timur - Kota Surabaya,Perempuan,12-24
3,#24 5Mar UI,SSXYPN,130404081822257332085165,1993,DKI Jakarta,Laki,lebih dari 24
4,#23 5Mar UI,IGGAXC,130404083224753556732599,1965,DKI Jakarta,Perempuan,1-2
...,...,...,...,...,...,...,...
655,Tuban-UNIROW-Oktober-2014,VHGHCS,160427175015254700996959,1993,Jawa Timur - Kabupaten Lamongan,Perempuan,1-2
656,Tuban-UNIROW-Oktober-2014,ZFTLQA,160427181142866467494470,1992,Jawa Tengah - Kabupaten Rembang,Perempuan,lebih dari 24
657,Tuban-UNIROW-Oktober-2014,KDYKSR,160427185152339369793142,1986,Jawa Timur - Kabupaten Bojonegoro,Perempuan,lebih dari 24
658,Tuban-UNIROW-Oktober-2014,BJRKZJ,160427191712877538854069,1992,Jawa Timur - Kabupaten Tuban,Perempuan,lebih dari 24
659,Tuban-UNIROW-Oktober-2014,EXAPWK,160427193323813373387464,1992,Jawa Timur - Kabupaten Lamongan,Perempuan,3-5

In [8]:
section9.columns = ['survey_location', 'session', 'id', 'birth_year', 'home_location', 'sex', 'visit_frequency']
section9 = section9.drop(columns=['id'])

section9

,survey_location,session,birth_year,home_location,sex,visit_frequency
0,NaN,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,NaN
1,#26 5Mar UI,XHMQVM,1993,Banten - Kota Tangerang,Laki,lebih dari 24
2,#25 5Mar UI,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,12-24
3,#24 5Mar UI,SSXYPN,1993,DKI Jakarta,Laki,lebih dari 24
4,#23 5Mar UI,IGGAXC,1965,DKI Jakarta,Perempuan,1-2
...,...,...,...,...,...,...
655,Tuban-UNIROW-Oktober-2014,VHGHCS,1993,Jawa Timur - Kabupaten Lamongan,Perempuan,1-2
656,Tuban-UNIROW-Oktober-2014,ZFTLQA,1992,Jawa Tengah - Kabupaten Rembang,Perempuan,lebih dari 24
657,Tuban-UNIROW-Oktober-2014,KDYKSR,1986,Jawa Timur - Kabupaten Bojonegoro,Perempuan,lebih dari 24
658,Tuban-UNIROW-Oktober-2014,BJRKZJ,1992,Jawa Timur - Kabupaten Tuban,Perempuan,lebih dari 24
659,Tuban-UNIROW-Oktober-2014,EXAPWK,1992,Jawa Timur - Kabupaten Lamongan,Perempuan,3-5

In [9]:
sections1_9 = sections1_7.merge(section9, how='left')

cols = [
    'survey_location',
    'session',
    'birth_year',
    'home_location',
    'sex',
    'caretaker',
    'visit_frequency',
    'relative_type',
    'relative_curr_home_lang',
    'relative_past_home_lang',
    'relative_work_lang',
    'relative_neighbor_lang',
    'relative_partner_lang',
    'relative_family_lang',
    'relative_ethnicity',
    'relative_education',
    'relative_past_home',
    'relative_curr_home',
    'relative_profession',
    'relative_religion',
    'relative_birth_year',
    'relative_first_lang',
    'relative_other_langs'
]

sections1_9 = sections1_9[cols]

sections1_9.head(20)

,survey_location,session,birth_year,home_location,sex,caretaker,visit_frequency,relative_type,relative_curr_home_lang,relative_past_home_lang,...,relative_family_lang,relative_ethnicity,relative_education,relative_past_home,relative_curr_home,relative_profession,relative_religion,relative_birth_year,relative_first_lang,relative_other_langs
0,NaN,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN,Ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
8,#26 5Mar UI,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,lebih dari 24,Ibu,NaN,NaN,...,NaN,Betawi,SMA,DKI Jakarta,Banten - Kota Tangerang,ibu rumah tangga,Islam,1953,Bahasa Betawi,Bahasa Indonesia
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,NaN,NaN,...,NaN,Jawa,sarjana,Jawa Timur,Banten - Kota Tangerang,pegawai swasta,Islam,1957,Bahasa Jawa,Bahasa Indonesia
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
16,#25 5Mar UI,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,12-24,Ibu,Bahasa Jawa,Bahasa Jawa,...,Bahasa Jawa,Jawa,S1,Daerah Istimewa Yogyakarta - Kota Yogyakarta,Jawa Barat - Kota Bekasi,ibu rumah tangga,Kristen (Katolik),1968,Bahasa Indonesia,Bahasa Jawa
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,Bahasa Jawa,Bahasa Jawa,...,Bahasa Jawa,Jawa,S1,Jawa Tengah - Kota Surakarta,Jawa Barat - Kota Bekasi,Manager HRD,Kristen (Katolik),1965,Bahasa Indonesia,Bahasa Jawa
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,Jawa,NaN,,Daerah Istimewa Yogyakarta - Kota Yogyakarta,observer,Kristen (Katolik),1951,Bahasa Indonesia,Bahasa Jawa
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,Bahasa Jawa,Bahasa Jawa

In [10]:
sections1_9.to_csv('allquestionnaires_sections1-9.csv', index=False)

In [11]:
sections1_9 = sections1_9.iloc[:, 1:7]
sections1_9.head(20)

,session,birth_year,home_location,sex,caretaker,visit_frequency
0,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,lebih dari 24
9,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN
16,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,12-24
17,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
sections1_9 = sections1_9.loc[sections1_9['session'].notnull()]
sections1_9

,session,birth_year,home_location,sex,caretaker,visit_frequency
0,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN
8,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,lebih dari 24
16,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,12-24
24,SSXYPN,1993,DKI Jakarta,Laki,Keluarga,lebih dari 24
32,IGGAXC,1965,DKI Jakarta,Perempuan,Orang tua,1-2
...,...,...,...,...,...,...
5256,VHGHCS,1993,Jawa Timur - Kabupaten Lamongan,Perempuan,Orangtua,1-2
5264,ZFTLQA,1992,Jawa Tengah - Kabupaten Rembang,Perempuan,Orangtua,lebih dari 24
5272,KDYKSR,1986,Jawa Timur - Kabupaten Bojonegoro,Perempuan,Orangtua,lebih dari 24
5280,BJRKZJ,1992,Jawa Timur - Kabupaten Tuban,Perempuan,Orangtua,lebih dari 24
5288,EXAPWK,1992,Jawa Timur - Kabupaten Lamongan,Perempuan,Wiraswasta,3-5

In [13]:
sections1_9.to_csv('allquestionnaires_sections1-9_abridged.csv', index=False)

In [14]:
usage = pd.read_csv('Usage.csv', header=None, dtype=str)
usage.head(40)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,IMQYYL,1.30403E+23,1991,Jawa Barat - Kota Depok,Laki,Indonesia,Sangat lancar,Sangat lancar,Sangat lancar,Lancar,dengan ibu,Indonesia
1,NaN,NaN,NaN,NaN,NaN,NaN,Inggris,Lancar,Lancar,Lancar,Lancar,dengan bapak,Indonesia
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan kakak/adik,Indonesia
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan nenek dan kakek,Indonesia
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan suami/istri (kalau sudah menikah),NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"dengan sanak saudara (tante, om, sepupu, dll)",Indonesia
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan tetangga,Indonesia
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan pembantu,Indonesia
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apabila marah,Inggris
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dalam mimpi,Inggris
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,berhitung,Indonesia
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kirim sms ke keluarga,Indonesia
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kirim sms ke teman,Inggris
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kirim sms ke suami/istri,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dalam jejaring sosial (FB),Inggris
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,berdoa dalam hati,Indonesia
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,berdoa di tempat ibadah,Indonesia
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di rumah,Indonesia
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di tempat kerja,Inggris
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di pasar,Indonesia
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di warung,Indonesia
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di bank,Indonesia
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di kantor pos,Indonesia
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di SD dengan guru,Indonesia
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di SD dengan teman sekelas,Indonesia
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di SMA dengan guru,Indonesia
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di SMA dengan teman sekelas,Indonesia
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di kendaraan umum,Indonesia
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca novel/buku cerita,Indonesia
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca koran,Inggris
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca majalah,Inggris
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mendengar musik,Inggris
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mendengar radio,Indonesia
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,menonton TV,Indonesia
34,#26 5Mar UI,XHMQVM,1.30404E+23,1993,Banten - Kota Tangerang,Laki,Bahasa Indonesia,Sangat lancar,Sangat lancar,Sangat lancar,Sangat lancar,dengan ibu,"Bahasa Indonesia, Bahasa Betawi"
35,NaN,NaN,NaN,NaN,NaN,NaN,Bahasa Betawi,Lancar,Lancar,Lancar,Agak lancar,dengan bapak,Bahasa Indonesia
36,NaN,NaN,NaN,NaN,NaN,NaN,Bahasa Sunda,Sedikit lancar,Sedikit lancar,Sedikit lancar,Tidak bisa,dengan kakak/adik,Bahasa Indonesia
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan nenek dan kakek,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan suami/istri (kalau sudah menikah),NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"dengan sanak saudara (tante, om, sepupu, dll)",Bahasa Indonesia

In [15]:
usage.columns = [
    'survey_location',
    'session',
    'id',
    'birth_year',
    'home_location',
    'sex',
    'prof_lang',
    'prof_understand',
    'prof_speak',
    'prof_read',
    'prof_write',
    'domain',
    'domain_lang'
]

usage

,survey_location,session,id,birth_year,home_location,sex,prof_lang,prof_understand,prof_speak,prof_read,prof_write,domain,domain_lang
0,NaN,IMQYYL,1.30403E+23,1991,Jawa Barat - Kota Depok,Laki,Indonesia,Sangat lancar,Sangat lancar,Sangat lancar,Lancar,dengan ibu,Indonesia
1,NaN,NaN,NaN,NaN,NaN,NaN,Inggris,Lancar,Lancar,Lancar,Lancar,dengan bapak,Indonesia
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan kakak/adik,Indonesia
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan nenek dan kakek,Indonesia
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan suami/istri (kalau sudah menikah),NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca koran,Indonesia
22436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca majalah,Indonesia
22437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mendengar musik,"Indonesia, India, Inggris, Korea"
22438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mendengar radio,Indonesia
22439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,menonton TV,"Indonesia, India, Inggris, Korea"

In [16]:
usage = usage.drop(columns=[
    'survey_location',
    'id',
    'prof_lang',
    'prof_understand',
    'prof_speak',
    'prof_read',
    'prof_write'
])

usage

,session,birth_year,home_location,sex,domain,domain_lang
0,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,dengan ibu,Indonesia
1,NaN,NaN,NaN,NaN,dengan bapak,Indonesia
2,NaN,NaN,NaN,NaN,dengan kakak/adik,Indonesia
3,NaN,NaN,NaN,NaN,dengan nenek dan kakek,Indonesia
4,NaN,NaN,NaN,NaN,dengan suami/istri (kalau sudah menikah),NaN
...,...,...,...,...,...,...
22435,NaN,NaN,NaN,NaN,membaca koran,Indonesia
22436,NaN,NaN,NaN,NaN,membaca majalah,Indonesia
22437,NaN,NaN,NaN,NaN,mendengar musik,"Indonesia, India, Inggris, Korea"
22438,NaN,NaN,NaN,NaN,mendengar radio,Indonesia
22439,NaN,NaN,NaN,NaN,menonton TV,"Indonesia, India, Inggris, Korea"

In [17]:
usage.to_csv('usage_abridged.csv', index=False)

At this point I did a bunch of manual editing in the Numbers application to "unpack" the relatives' speech habits into a more usable format.

In [27]:
usages_unpacked = pd.read_csv('allquestionnaires_sections1-9_unpacked_usages.csv', dtype=str)
usages_unpacked

,session,birth_year,home_location,sex,caretaker,visit_frequency,ibu_curr_home_lang,ibu_past_home_lang,ibu_work_lang,ibu_neighbor_lang,...,di_sd_dengan_teman_sekelas_lang,di_sma_dengan_guru_lang,di_sma_dengan_teman_sekelas_lang,di_kendaraan_umum_lang,membaca_novel_lang,membaca_koran_lang,membaca_majalah_lang,mendengar_musik_lang,mendengar_radio_lang,menonton_tv_lang
0,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN,NaN,NaN,NaN,NaN,...,Indonesia,Indonesia,Indonesia,Indonesia,Indonesia,Inggris,Inggris,Inggris,Indonesia,Indonesia
1,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,lebih dari 24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Bahasa Indonesia,NaN,NaN,Bahasa Inggris,NaN,NaN
2,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,12-24,Bahasa Jawa,Bahasa Jawa,Bahasa Indonesia,Bahasa Indonesia,...,"Bahasa Indonesia, Bahasa Jawa",Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,"Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris",Bahasa Indonesia,"Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris"
3,SSXYPN,1993,DKI Jakarta,Laki,Keluarga,lebih dari 24,"Bahasa Indonesia, Bahasa Minang",Bahasa Minang,Bahasa Indonesia,Bahasa Indonesia,...,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia
4,IGGAXC,1965,DKI Jakarta,Perempuan,Orang tua,1-2,"Bahasa Indonesia, Bahasa Sunda",Bahasa Sunda,Bahasa Indonesia,Bahasa Indonesia,...,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,"Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,VHGHCS,1993,Jawa Timur - Kabupaten Lamongan,Perempuan,Orangtua,1-2,Jawa,Jawa,NaN,Jawa,...,Jawa,"Indonesia, Jawa","Indonesia, Jawa",Jawa,"Inggris, Indonesia, Jawa","Indonesia, Inggris",Indonesia,"Indonesia, Inggris",Indonesia,"Indonesia, Jawa"
656,ZFTLQA,1992,Jawa Tengah - Kabupaten Rembang,Perempuan,Orangtua,lebih dari 24,Jawa,Jawa,NaN,Jawa,...,"Jawa, Indonesia",Indonesia,"Jawa, Indonesia",Indonesia,"Indonesia, Inggris",Indonesia,Indonesia,"Indonesia, Inggris",Indonesia,Indonesia
657,KDYKSR,1986,Jawa Timur - Kabupaten Bojonegoro,Perempuan,Orangtua,lebih dari 24,Jawa,Jawa,NaN,Jawa,...,"Jawa, Indonesia",Indonesia,"Jawa, Indonesia",Jawa,"Indonesia, Inggris","Indonesia, Inggris","Indonesia, Inggris","Indonesia, Inggris",Indonesia,"Indonesia, Inggris"
658,BJRKZJ,1992,Jawa Timur - Kabupaten Tuban,Perempuan,Orangtua,lebih dari 24,"Jawa, Indonesia",Jawa,"Jawa, Indonesia",Jawa,...,"Jawa, Indonesia",Indonesia,"Jawa, Indonesia",Indonesia,"Indonesia, Inggris",Indonesia,Indonesia,"Indonesia, Inggris",Indonesia,"Indonesia, Inggris"
659,EXAPWK,1992,Jawa Timur - Kabupaten Lamongan,Perempuan,Wiraswasta,3-5,Jawa,"Jawa, Indonesia",NaN,Jawa,...,Jawa,Indonesia,"Jawa, Indonesia",Jawa,Indonesia,Indonesia,Indonesia,"Indonesia, India, Inggris, Korea",Indonesia,"Indonesia, India, Inggris, Korea"

In [28]:
import re

def clean(s: str) -> str:
    if pd.isna(s):
        return s
    else:
        s = s.lower()
        s = re.sub('baha?sa', '', s)
        s = re.sub('b\.', '', s)
        s = re.sub('bhs', '', s)
        s = re.sub('dialek', '', s)
        s = re.sub('/', ',', s)
        s = re.sub('dan', ',', s)
        s = re.sub(', *,', ',', s)
        s = s.strip()
        s = re.sub('  +', ' ', s)
        s = re.sub(',$', '', s)
        return s

usages_unpacked = usages_unpacked.applymap(clean)
usages_unpacked

,session,birth_year,home_location,sex,caretaker,visit_frequency,ibu_curr_home_lang,ibu_past_home_lang,ibu_work_lang,ibu_neighbor_lang,...,di_sd_dengan_teman_sekelas_lang,di_sma_dengan_guru_lang,di_sma_dengan_teman_sekelas_lang,di_kendaraan_umum_lang,membaca_novel_lang,membaca_koran_lang,membaca_majalah_lang,mendengar_musik_lang,mendengar_radio_lang,menonton_tv_lang
0,imqyyl,1991,jawa barat - kota depok,laki,orang tua,NaN,NaN,NaN,NaN,NaN,...,indonesia,indonesia,indonesia,indonesia,indonesia,inggris,inggris,inggris,indonesia,indonesia
1,xhmqvm,1993,banten - kota tangerang,laki,orang tua,lebih dari 24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,indonesia,NaN,NaN,inggris,NaN,NaN
2,oqhpqe,1995,jawa timur - kota surabaya,perempuan,orang tua,12-24,jawa,jawa,indonesia,indonesia,...,"indonesia, jawa",indonesia,indonesia,indonesia,"indonesia, inggris","indonesia, inggris",indonesia,"indonesia, inggris","indonesia, inggris","indonesia, inggris"
3,ssxypn,1993,dki jakarta,laki,keluarga,lebih dari 24,"indonesia, minang",minang,indonesia,indonesia,...,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia
4,iggaxc,1965,dki jakarta,perempuan,orang tua,1-2,"indonesia, sunda",sunda,indonesia,indonesia,...,indonesia,indonesia,indonesia,indonesia,"indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,vhghcs,1993,jawa timur - kabupaten lamongan,perempuan,orangtua,1-2,jawa,jawa,NaN,jawa,...,jawa,"indonesia, jawa","indonesia, jawa",jawa,"inggris, indonesia, jawa","indonesia, inggris",indonesia,"indonesia, inggris",indonesia,"indonesia, jawa"
656,zftlqa,1992,jawa tengah - kabupaten rembang,perempuan,orangtua,lebih dari 24,jawa,jawa,NaN,jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",indonesia,"indonesia, inggris",indonesia,indonesia,"indonesia, inggris",indonesia,indonesia
657,kdyksr,1986,jawa timur - kabupaten bojonegoro,perempuan,orangtua,lebih dari 24,jawa,jawa,NaN,jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",jawa,"indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris",indonesia,"indonesia, inggris"
658,bjrkzj,1992,jawa timur - kabupaten tuban,perempuan,orangtua,lebih dari 24,"jawa, indonesia",jawa,"jawa, indonesia",jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",indonesia,"indonesia, inggris",indonesia,indonesia,"indonesia, inggris",indonesia,"indonesia, inggris"
659,exapwk,1992,jawa timur - kabupaten lamongan,perempuan,wiraswasta,3-5,jawa,"jawa, indonesia",NaN,jawa,...,jawa,indonesia,"jawa, indonesia",jawa,indonesia,indonesia,indonesia,"indonesia, india, inggris, korea",indonesia,"indonesia, india, inggris, korea"

In [29]:
usages_unpacked.to_csv('usages_unpacked_cleaned.csv', index=False)

## Data Analysis

In [4]:
import pandas as pd
import re

usages_unpacked = pd.read_csv('usages_unpacked_cleaned.csv', dtype=str)

In [5]:
def unpack(s: str) -> frozenset[str]:
    if pd.isna(s):
        return frozenset()
    else:
        langs = re.split(' *, *', s)
        return frozenset(langs)

In [6]:
context_langs = usages_unpacked.iloc[:, 6:].applymap(unpack)
context_langs

,ibu_curr_home_lang,ibu_past_home_lang,ibu_work_lang,ibu_neighbor_lang,ibu_partner_lang,ibu_family_lang,ibu_ethnicity,ibu_education,ibu_past_home,ibu_curr_home,...,di_sd_dengan_teman_sekelas_lang,di_sma_dengan_guru_lang,di_sma_dengan_teman_sekelas_lang,di_kendaraan_umum_lang,membaca_novel_lang,membaca_koran_lang,membaca_majalah_lang,mendengar_musik_lang,mendengar_radio_lang,menonton_tv_lang
0,(),(),(),(),(),(),(),(),(),(),...,(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(inggris),(inggris),(inggris),(indonesia),(indonesia)
1,(),(),(),(),(),(),(betawi),(sma),(dki jakarta),(banten - kota tangerang),...,(),(),(),(),(indonesia),(),(),(inggris),(),()
2,(jawa),(jawa),(indonesia),(indonesia),(jawa),(jawa),(jawa),(s1),(daerah istimewa yogyakarta - kota yogyakarta),(jawa barat - kota bekasi),...,"(indonesia, jawa)",(indonesia),(indonesia),(indonesia),"(indonesia, inggris)","(indonesia, inggris)",(indonesia),"(indonesia, inggris)","(indonesia, inggris)","(indonesia, inggris)"
3,"(indonesia, minang)",(minang),(indonesia),(indonesia),"(indonesia, minang)",(minang),(minang),(s1),"(sumatera barat - kota pa, g)",(dki jakarta),...,(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia)
4,"(indonesia, sunda)",(sunda),(indonesia),(indonesia),"(indonesia, sunda)","(indonesia, sunda)",(sunda),(diploma),(jawa barat - kabupaten cianjur),(dki jakarta),...,(indonesia),(indonesia),(indonesia),(indonesia),"(indonesia, inggris)","(indonesia, inggris)","(indonesia, inggris)","(indonesia, inggris)","(indonesia, inggris)","(indonesia, inggris)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,(jawa),(jawa),(),(jawa),(jawa),"(indonesia, jawa)",(jawa),(sma),(jawa timur - kabupaten lamongan),(jawa timur - kabupaten lamongan),...,(jawa),"(indonesia, jawa)","(indonesia, jawa)",(jawa),"(inggris, jawa, indonesia)","(indonesia, inggris)",(indonesia),"(indonesia, inggris)",(indonesia),"(indonesia, jawa)"
656,(jawa),(jawa),(),(jawa),(jawa),(jawa),(jawa),(smp),(jawa tengah - kabupaten rembang),(jawa tengah - kabupaten rembang),...,"(indonesia, jawa)",(indonesia),"(indonesia, jawa)",(indonesia),"(indonesia, inggris)",(indonesia),(indonesia),"(indonesia, inggris)",(indonesia),(indonesia)
657,(jawa),(jawa),(),(jawa),(jawa),(jawa),(jawa),(smp),(jawa timur - kabupaten bojonegoro),(jawa timur - kabupaten bojonegoro),...,"(indonesia, jawa)",(indonesia),"(indonesia, jawa)",(jawa),"(indonesia, inggris)","(indonesia, inggris)","(indonesia, inggris)","(indonesia, inggris)",(indonesia),"(indonesia, inggris)"
658,"(indonesia, jawa)",(jawa),"(indonesia, jawa)",(jawa),"(indonesia, jawa)",(indonesia),(jawa),(smu),(jawa timur - kabupaten tuban),(jawa timur - kabupaten tuban),...,"(indonesia, jawa)",(indonesia),"(indonesia, jawa)",(indonesia),"(indonesia, inggris)",(indonesia),(indonesia),"(indonesia, inggris)",(indonesia),"(indonesia, inggris)"
659,(jawa),"(indonesia, jawa)",(),(jawa),(jawa),"(indonesia, jawa)",(jawa),(sma),(jawa timur - kabupaten tuban),(jawa timur - kabupaten lamongan),...,(jawa),(indonesia),"(indonesia, jawa)",(jawa),(indonesia),(indonesia),(indonesia),"(indonesia, korea, india, inggris)",(indonesia),"(indonesia, korea, india, inggris)"

In [7]:
for i, header in enumerate(context_langs):
    print(i, header)

0 ibu_curr_home_lang
1 ibu_past_home_lang
2 ibu_work_lang
3 ibu_neighbor_lang
4 ibu_partner_lang
5 ibu_family_lang
6 ibu_ethnicity
7 ibu_education
8 ibu_past_home
9 ibu_curr_home
10 ibu_profession
11 ibu_religion
12 ibu_birth_year
13 ibu_first_lang
14 ibu_other_langs
15 bapak_curr_home_lang
16 bapak_past_home_lang
17 bapak_work_lang
18 bapak_neighbor_lang
19 bapak_partner_lang
20 bapak_family_lang
21 bapak_ethnicity
22 bapak_education
23 bapak_past_home
24 bapak_curr_home
25 bapak_profession
26 bapak_religion
27 bapak_birth_year
28 bapak_first_lang
29 bapak_other_langs
30 ibu_dari_ibu_curr_home_lang
31 ibu_dari_ibu_past_home_lang
32 ibu_dari_ibu_work_lang
33 ibu_dari_ibu_neighbor_lang
34 ibu_dari_ibu_partner_lang
35 ibu_dari_ibu_family_lang
36 ibu_dari_ibu_ethnicity
37 ibu_dari_ibu_education
38 ibu_dari_ibu_past_home
39 ibu_dari_ibu_curr_home
40 ibu_dari_ibu_profession
41 ibu_dari_ibu_religion
42 ibu_dari_ibu_birth_year
43 ibu_dari_ibu_first_lang
44 ibu_dari_ibu_other_langs
45 bapak_dari_ibu_curr_home_lang
46 bapak_dari_ibu_past_home_lang
47 bapak_dari_ibu_work_lang
48 bapak_dari_ibu_neighbor_lang
49 bapak_dari_ibu_partner_lang
50 bapak_dari_ibu_family_lang
51 bapak_dari_ibu_ethnicity
52 bapak_dari_ibu_education
53 bapak_dari_ibu_past_home
54 bapak_dari_ibu_curr_home
55 bapak_dari_ibu_profession
56 bapak_dari_ibu_religion
57 bapak_dari_ibu_birth_year
58 bapak_dari_ibu_first_lang
59 bapak_dari_ibu_other_langs
60 ibu_dari_bapak_curr_home_lang
61 ibu_dari_bapak_past_home_lang
62 ibu_dari_bapak_work_lang
63 ibu_dari_bapak_neighbor_lang
64 ibu_dari_bapak_partner_lang
65 ibu_dari_bapak_family_lang
66 ibu_dari_bapak_ethnicity
67 ibu_dari_bapak_education
68 ibu_dari_bapak_past_home
69 ibu_dari_bapak_curr_home
70 ibu_dari_bapak_profession
71 ibu_dari_bapak_religion
72 ibu_dari_bapak_birth_year
73 ibu_dari_bapak_first_lang
74 ibu_dari_bapak_other_langs
75 bapak_dari_bapak_curr_home_lang
76 bapak_dari_bapak_past_home_lang
77 bapak_dari_bapak_work_lang
78 bapak_dari_bapak_neighbor_lang
79 bapak_dari_bapak_partner_lang
80 bapak_dari_bapak_family_lang
81 bapak_dari_bapak_ethnicity
82 bapak_dari_bapak_education
83 bapak_dari_bapak_past_home
84 bapak_dari_bapak_curr_home
85 bapak_dari_bapak_profession
86 bapak_dari_bapak_religion
87 bapak_dari_bapak_birth_year
88 bapak_dari_bapak_first_lang
89 bapak_dari_bapak_other_langs
90 dengan_ibu_lang
91 dengan_bapak_lang
92 dengan_kakak_adik_lang
93 dengan_nenek_dan_kakek_lang
94 dengan_suami_istri_lang
95 dengan_sanak_saudara_lang
96 dengan_tetangga_lang
97 dengan_pembantu_lang
98 apabila_marah_lang
99 dalam_mimpi_lang
100 berhitung_lang
101 kirim_sms_ke_keluarga_lang
102 kirim_sms_ke_teman_lang
103 kirim_sms_ke_suami_istri_lang
104 dalam_jejaring_sosial_lang
105 berdoa_dalam_hati_lang
106 berdoa_di_tempat_ibadah_lang
107 di_rumah_lang
108 di_tempat_kerja_lang
109 di_pasar_lang
110 di_warung_lang
111 di_bank_lang
112 di_kantor_pos_lang
113 di_sd_dengan_guru_lang
114 di_sd_dengan_teman_sekelas_lang
115 di_sma_dengan_guru_lang
116 di_sma_dengan_teman_sekelas_lang
117 di_kendaraan_umum_lang
118 membaca_novel_lang
119 membaca_koran_lang
120 membaca_majalah_lang
121 mendengar_musik_lang
122 mendengar_radio_lang
123 menonton_tv_lang

In [8]:
import numpy as np

def langs_in_row(context_langs: pd.DataFrame) -> pd.DataFrame:
    lang_sets = np.empty(len(context_langs), dtype=frozenset)
    for index, row in context_langs.iterrows():
        langs = set()
        for entry in row:
            langs |= entry

        lang_sets[index] = frozenset(langs)

    return pd.DataFrame(lang_sets, columns=['languages'])

In [9]:
from collections import defaultdict
from more_itertools import powerset
import re

class PerceptronTrainer:
    def __init__(self, ibu_data: pd.DataFrame,
                 respondent_data: pd.DataFrame,
                 ibu_dari_ibu_data: pd.DataFrame,
                 ibu_dari_bapak_data: pd.DataFrame) -> None:
        self.ibu_dari_ibu_maps = self.context_map(ibu_dari_ibu_data)
        self.ibu_dari_bapak_maps = self.context_map(ibu_dari_bapak_data)
        self.ibu_maps = self.context_map(ibu_data)
        self.respondent_maps = self.context_map(respondent_data)
        self.weights = defaultdict(int)
        self.contexts = {header for header in respondent_data}
        self.tags = [frozenset(contexts) for contexts in powerset(self.contexts)]

    def context_map(self, data: pd.DataFrame) -> pd.DataFrame:
        '''
        Maps the language labels in each row of a DataFrame to
        their corresponding context sets
        '''
        maps = np.empty(len(data), dtype=dict)
        for i, row in data.iterrows():
            cmap = defaultdict(frozenset)
            for j, entry in enumerate(row):
                for lang in entry:
                    cmap[lang] |= {data.columns[j]}

            for lang in cmap:
                cmap[lang] = frozenset(cmap[lang])

            maps[i] = cmap

        return pd.DataFrame(maps, columns=['context_maps'])

    def viterbi(self, langs: list[str], row: int) -> tuple[int, list[frozenset[str]]]:
        '''
        Finds the optimal sequence of context sets for the given list of languages
        '''

        # Initialize the delta table
        deltas = {(tag, -1): (float('-inf'), []) for tag in self.tags}
        deltas[frozenset('START'), -1] = 0.0, []

        def get_delta(curr_tag: frozenset[str], curr_idx: int) -> tuple[int, list[frozenset[str]]]:
            '''
            Helper method for the viterbi method
            '''

            if (curr_tag, curr_idx) in deltas:
                return deltas[curr_tag, curr_idx]

            else:
                # Get all possible cumulative Viterbi scores for curr_tag and curr_idx
                candidates = []
                for prev_tag in self.tags + [frozenset('START')]:
                    prev_delta, back_pointer = get_delta(prev_tag, curr_idx - 1)
                    ibu_dari_ibu_set = self.ibu_dari_ibu_maps.iloc[row, 0][langs[curr_idx]]
                    ibu_dari_bapak_set = self.ibu_dari_bapak_maps.iloc[row, 0][langs[curr_idx]]
                    ibu_set = self.ibu_maps.iloc[row, 0][langs[curr_idx]]

                    # Calculate the score for the current tag under consideration
                    curr_score = 0
                    curr_score += self.weights['emits', curr_tag, langs[curr_idx]]
                    curr_score += self.weights['subset', curr_tag, ibu_set]
                    curr_score += self.weights['superset', curr_tag, ibu_set]
                    curr_score += self.weights['subset', curr_tag, ibu_dari_ibu_set]
                    curr_score += self.weights['superset', curr_tag, ibu_dari_ibu_set]
                    curr_score += self.weights['subset', curr_tag, ibu_dari_bapak_set]
                    curr_score += self.weights['superset', curr_tag, ibu_dari_bapak_set]
                    #curr_score += self.weights['equal', curr_tag, ibu_set]
                    for context in curr_tag:
                        curr_score += self.weights['in', context, langs[curr_idx]]

                    # Add the current score to the best previous score and save it
                    candidates.append((prev_delta + curr_score, back_pointer + [curr_tag]))

                # Store and return the maximum score found
                deltas[curr_tag, curr_idx] = max(candidates, key=lambda x: x[0])
                return deltas[curr_tag, curr_idx]

        # Fill in the delta table
        for idx in range(len(langs)):
            for tag in self.tags:
                get_delta(tag, idx)

        # Return the maximum delta value that's in the final column of the table
        return max([deltas[tag, idx] for tag, idx in deltas if idx == len(langs) - 1],
                   key=lambda x: x[0])

    def train_to(self, filename: str) -> None:
        '''
        Starts training over the data set and writes checkpoints
        to files name after the specified filename
        '''
        curr_iter, num_wrong_tags = 0, 1
        while num_wrong_tags > 0:
            num_wrong_tags, num_wrong_sequences = 0, 0
            print(f'Working on iteration {curr_iter}...')

            for i, row in self.respondent_maps.iterrows():
                ibu_cmap = self.ibu_maps.iloc[i, 0]
                ibu_dari_ibu_cmap = self.ibu_dari_ibu_maps.iloc[i, 0]
                ibu_dari_bapak_cmap = self.ibu_dari_bapak_maps.iloc[i, 0]
                respondent_cmap = row[0]
                for lang in respondent_cmap:
                    ibu_cmap[lang] |= frozenset()

                for lang in ibu_cmap:
                    ibu_dari_ibu_cmap[lang] |= frozenset()
                    
                for lang in ibu_dari_ibu_cmap:
                    ibu_dari_bapak_cmap[lang] |= frozenset()

                cmap_entries = [(lang, respondent_cmap[lang]) for lang in ibu_dari_bapak_cmap]
                langs = [entry[0] for entry in cmap_entries]
                gold_tags = [entry[1] for entry in cmap_entries]

                _, estimated_tags = self.viterbi(langs, i)
                if gold_tags != estimated_tags:
                    num_wrong_sequences += 1
                    gold_tags = [frozenset('START')] + gold_tags
                    estimated_tags = [frozenset('START')] + estimated_tags
                    for j in range(len(langs)):
                        ibu_set = self.ibu_maps.iloc[i, 0][langs[j]]
                        ibu_dari_ibu_set = self.ibu_dari_ibu_maps.iloc[i, 0][langs[j]]
                        ibu_dari_bapak_set = self.ibu_dari_bapak_maps.iloc[i, 0][langs[j]]

                        # Emissions
                        self.weights['emits', gold_tags[j + 1], langs[j]] += 1
                        self.weights['emits', estimated_tags[j + 1], langs[j]] -= 1

                        # ibu Subsets
                        if gold_tags[j + 1] < ibu_set:
                            self.weights['subset', gold_tags[j + 1], ibu_set] += 1

                        if estimated_tags[j + 1] < ibu_set:
                            self.weights['subset', estimated_tags[j + 1], ibu_set] -= 1

                        # ibu Supersets
                        if gold_tags[j + 1] > ibu_set:
                            self.weights['superset', gold_tags[j + 1], ibu_set] += 1

                        if estimated_tags[j + 1] > ibu_set:
                            self.weights['superset', estimated_tags[j + 1], ibu_set] -= 1

                        # ibu dari ibu subsets
                        if gold_tags[j + 1] < ibu_dari_ibu_set:
                            self.weights['subset', gold_tags[j + 1], ibu_dari_ibu_set] += 1

                        if estimated_tags[j + 1] < ibu_dari_ibu_set:
                            self.weights['subset', estimated_tags[j + 1], ibu_dari_ibu_set] -= 1

                        # ibu dari ibu supersets
                        if gold_tags[j + 1] > ibu_dari_ibu_set:
                            self.weights['superset', gold_tags[j + 1], ibu_dari_ibu_set] += 1

                        if estimated_tags[j + 1] > ibu_dari_ibu_set:
                            self.weights['superset', estimated_tags[j + 1], ibu_dari_ibu_set] -= 1
                            
                        # ibu dari bapak subsets
                        if gold_tags[j + 1] < ibu_dari_bapak_set:
                            self.weights['subset', gold_tags[j + 1], ibu_dari_bapak_set] += 1

                        if estimated_tags[j + 1] < ibu_dari_bapak_set:
                            self.weights['subset', estimated_tags[j + 1], ibu_dari_bapak_set] -= 1

                        # ibu dari bapak supersets
                        if gold_tags[j + 1] > ibu_dari_bapak_set:
                            self.weights['superset', gold_tags[j + 1], ibu_dari_bapak_set] += 1

                        if estimated_tags[j + 1] > ibu_dari_bapak_set:
                            self.weights['superset', estimated_tags[j + 1], ibu_dari_bapak_set] -= 1

                        # Equals
                        if gold_tags[j + 1] == ibu_set:
                            self.weights['equals', gold_tags[j + 1], ibu_set] += 1

                        if estimated_tags[j + 1] == ibu_set:
                            self.weights['equals', estimated_tags[j + 1], ibu_set] -= 1
                        
                        for context in gold_tags[j + 1]:
                            self.weights['in', context, langs[j]] += 1
                        
                        for context in estimated_tags[j + 1]:
                            self.weights['in', context, langs[j]] -= 1


                        # Count number of individual tags that are wrong
                        if gold_tags[j + 1] != estimated_tags[j + 1]:
                            num_wrong_tags += 1

            # Output a new (sorted) feature weights file
            with open(f'{filename}{curr_iter}.txt', 'w') as file:
                emissions = [feature for feature in self.weights
                            if feature[0] == 'emits' and feature[1] != frozenset('START')]
                subsets = [feature for feature in self.weights
                           if feature[0] == 'subset' and feature[1] != frozenset('START')]
                supersets = [feature for feature in self.weights
                             if feature[0] == 'superset' and feature[1] != frozenset('START')]
                #equals = [feature for feature in self.weights
                #             if feature[0] == 'equals' and feature[1] != frozenset('START')]
                ins = [feature for feature in self.weights
                             if feature[0] == 'in' and feature[1] != 'START']

                # Write valid emission features first
                for emission in sorted(emissions, key=lambda x: (self.tags.index(x[1]), x[2])):
                    file.write(f'{emission} {self.weights[emission]}\n')

                # Then subset features
                for subset in sorted(subsets, key=lambda x: (self.tags.index(x[1]), x[2])):
                    file.write(f'{subset} {self.weights[subset]}\n')

                # Then superset features
                for superset in sorted(supersets, key=lambda x: (self.tags.index(x[1]), x[2])):
                    file.write(f'{superset} {self.weights[superset]}\n')

                #for equal in sorted(equals, key=lambda x: (self.tags.index(x[1]), x[2])):
                #    file.write(f'{equal} {self.weights[equal]}\n')
                
                for in_feat in sorted(ins, key=lambda x: (x[1], x[2])):
                    file.write(f'{in_feat} {self.weights[in_feat]}\n')

            # Print minimal debug info to standard output
            plural_tags = 's' if num_wrong_tags != 1 else ''
            plural_sequences = 's' if num_wrong_sequences != 1 else ''
            print(f'Finished iteration {curr_iter} with {num_wrong_tags} incorrect tag{plural_tags}',
                  f'and {num_wrong_sequences} incorrect tag sequence{plural_sequences}')

            curr_iter += 1

    def load_weights(self, filename: str) -> None:
        '''
        Loads a set of saved weights from the specified weights file
        '''
        with open(filename) as file:
            pattern = re.compile(r'(\(.*\)) (-?\d+)')
            for line in file:
                match = re.fullmatch(pattern, line.strip())
                lang_set, score = match[1], match[2]
                self.weights[eval(lang_set)] = int(score)

    def tag_langs(self, context_langs: pd.DataFrame) -> None:
        '''
        Tags the specified DataFrame of language labels
        using the weights stored in memory
        '''
        cmap = self.context_map(context_langs)
        ratios_correct, num_tagged = [], 0
        precision_ratios, recall_ratios = [], []
        langs = langs_in_row(context_langs)
        for i, row in langs.iterrows():
            num_correct = 0
            lang_list = list(row[0])
            max_score, sequence = self.viterbi(lang_list, i)
            num_tagged += 1
            precision = 0.0
            recall = 0.0
            for idx in range(len(sequence)):
                num_relevant = 0
                for context in sequence[idx]:
                    if context in cmap.iloc[i, 0][lang_list[idx]]:
                        num_relevant += 1

                if sequence[idx]:
                    precision += num_relevant / len(sequence[idx])
                    
                if cmap.iloc[i, 0][lang_list[idx]]:
                    recall += num_relevant / len(cmap.iloc[i, 0][lang_list[idx]])

                if sequence[idx] == cmap.iloc[i, 0][lang_list[idx]]:
                    num_correct += 1
                #else:
                #    print(sequence[idx], cmap.iloc[i, 0][lang_list[idx]])

            if len(lang_list) > 0:
                precision_ratios.append(precision / len(lang_list))
                recall_ratios.append(recall / len(lang_list))
                ratios_correct.append(num_correct / len(lang_list))

        if ratios_correct:
            print(f'Recorded accuracy: {sum(ratios_correct) / len(ratios_correct)}')
                                                    
        if precision_ratios:
            print(f'Recorded precision: {sum(precision_ratios) / len(precision_ratios)}')

        if recall_ratios:
            print(f'Recorded recall: {sum(recall_ratios) / len(recall_ratios)}')

In [10]:
shuffled_context_langs = context_langs.sample(frac=1.0).reset_index(drop=True)
shuffled_context_langs

,ibu_curr_home_lang,ibu_past_home_lang,ibu_work_lang,ibu_neighbor_lang,ibu_partner_lang,ibu_family_lang,ibu_ethnicity,ibu_education,ibu_past_home,ibu_curr_home,...,di_sd_dengan_teman_sekelas_lang,di_sma_dengan_guru_lang,di_sma_dengan_teman_sekelas_lang,di_kendaraan_umum_lang,membaca_novel_lang,membaca_koran_lang,membaca_majalah_lang,mendengar_musik_lang,mendengar_radio_lang,menonton_tv_lang
0,(tebing tinggi sum-sel),"(minang, tebing tinggi)",(tebing tinggi pasar),(tebing tinggi sum-sel),"(minang, tebing tinggi)","(indonesia, minang, tebing tinggi)","(minang, jambak)",(sd),(#name?),(- tebing tinggi 4 l),...,(tebing tinggi sum-sel),"(indonesia, tebing tinggi)",(tebing tinggi sum-sel),(indonesia),(indonesia),(indonesia),(indonesia),"(indonesia, tebing tinggi)","(indonesia, minang)","(indonesia, minang, tebing tinggi)"
1,(jawa),(jawa),(jawa),(jawa),(jawa),(jawa),(jawa),(sma),(jawa timur - kabupaten gresik),(jawa timur - kabupaten gresik),...,(jawa ngukuh),(jawa),(jawa ngukuh),(jawa ngukuh),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(jawa ngukuh)
2,(),(rote),(rote),(),(rote),(rote),(taraku),(sd),(nusa tenggara timur - kabupaten rote ndao),(nusa tenggara timur - kabupaten rote ndao),...,(rote),(indonesia),(kupang),(kupang),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia)
3,(ngoko),(ngoko),(ngoko),(ngoko),(ngoko),(ngoko),(jawa),(sd),(jawa tengah - kabupaten rembang),(jawa tengah - kabupaten rembang),...,(ngoko),(indonesia),(ngoko),(ngoko),(indonesia),(indonesia),(indonesia),"(inggris, indonesia)",(indonesia),(ngoko)
4,"(indonesia, minang)",(minang),(indonesia),"(indonesia, minang)","(indonesia, minang)","(indonesia, minang)",(minang),(sma),(sumatera barat - kabupaten pesisir selatan),(sumatera barat - kabupaten pesisir selatan),...,(indonesia),(indonesia),(minang),(indonesia),(indonesia),(indonesia),(indonesia),"(indonesia, inggris)",(indonesia),"(indonesia, inggris)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,(indonesia),(semendo),(),(indonesia),(indonesia),(indonesia),(semendo),(sma),(#name?),(lampung - kecamatan natar),...,(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(),()
656,(),(),(),(),(),(),(),(),(),(),...,(),(),(),(),(),(),(),(),(),()
657,"(indonesia, jawa)",(jawa),(),"(indonesia, jawa)",(jawa),"(indonesia, jawa)",(jawa),(sd),(#name?),(bengkulu - bengkulu utara),...,(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia)
658,(jawa),(jawa),(jawa),(jawa),(jawa),(jawa),(jawa),(smp),(jawa),(jawa tengah - kota magelang),...,(jawa),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia),(indonesia)
659,(jawa),(jawa),"(indonesia, jawa)",(jawa),(jawa),(jawa),(jawa),(sd),(jawa timur - kabupaten lamongan),(jawa timur - kabupaten lamongan),...,(jawa),(indonesia),(jawa),"(indonesia, jawa)",(sesuai dengan novel),(sesuai dengan koran),(sesuai dengan majalah),(sesuai dengan musik),(sesuai dengan radio),"(indonesia, inggris)"

In [11]:
ibu_train_data = shuffled_context_langs.iloc[:462, :6]
ibu_train_data = ibu_train_data.drop(columns=['ibu_past_home_lang'])
ibu_train_data.columns = [
    'di_rumah_lang',
    'di_tempat_kerja_lang',
    'dengan_tetangga_lang',
    'dengan_suami_istri_lang',
    'dengan_sanak_saudara_lang'
]
ibu_train_data

,di_rumah_lang,di_tempat_kerja_lang,dengan_tetangga_lang,dengan_suami_istri_lang,dengan_sanak_saudara_lang
0,(tebing tinggi sum-sel),(tebing tinggi pasar),(tebing tinggi sum-sel),"(minang, tebing tinggi)","(indonesia, minang, tebing tinggi)"
1,(jawa),(jawa),(jawa),(jawa),(jawa)
2,(),(rote),(),(rote),(rote)
3,(ngoko),(ngoko),(ngoko),(ngoko),(ngoko)
4,"(indonesia, minang)",(indonesia),"(indonesia, minang)","(indonesia, minang)","(indonesia, minang)"
...,...,...,...,...,...
457,"(jawa, madura)",(indonesia),(jawa),"(indonesia, madura)",(osing banyuwangi)
458,"(daerah, indonesia)","(daerah, indonesia)","(indonesia, bali)","(daerah, indonesia)","(daerah, indonesia)"
459,(minangkabau),(bengkulu selatan),(indonesia),(minangkabau),(minangkabau)
460,(),(),(jawa),(jawa),"(indonesia, jawa)"
461,(jawa),(jawa),(jawa),(jawa),(jawa)

In [12]:
ibu_dari_ibu_train_data = shuffled_context_langs.iloc[:462, 30:36]
ibu_dari_ibu_train_data = ibu_dari_ibu_train_data.drop(columns=['ibu_dari_ibu_past_home_lang'])
ibu_dari_ibu_train_data.columns = [
    'di_rumah_lang',
    'di_tempat_kerja_lang',
    'dengan_tetangga_lang',
    'dengan_suami_istri_lang',
    'dengan_sanak_saudara_lang'
]
ibu_dari_ibu_train_data

,di_rumah_lang,di_tempat_kerja_lang,dengan_tetangga_lang,dengan_suami_istri_lang,dengan_sanak_saudara_lang
0,(),(),(),(),()
1,(jawa),(jawa),(jawa),(jawa),(jawa)
2,(),(),(),(),()
3,(),(),(),(),()
4,(indonesia),(minang),(minang),(minang),(minang)
...,...,...,...,...,...
457,(osing banyuwangi),(osing banyuwangi),(osing banyuwangi),(osing banyuwangi),(osing banyuwangi)
458,(),(),(),(),()
459,(),(),(),(),()
460,(),(),(jawa),(jawa),(jawa)
461,(jawa),(),(jawa),(jawa),(jawa)

In [13]:
ibu_dari_bapak_train_data = shuffled_context_langs.iloc[:462, 60:66]
ibu_dari_bapak_train_data = ibu_dari_bapak_train_data.drop(columns=['ibu_dari_bapak_past_home_lang'])
ibu_dari_bapak_train_data.columns = [
    'di_rumah_lang',
    'di_tempat_kerja_lang',
    'dengan_tetangga_lang',
    'dengan_suami_istri_lang',
    'dengan_sanak_saudara_lang'
]
ibu_dari_bapak_train_data

,di_rumah_lang,di_tempat_kerja_lang,dengan_tetangga_lang,dengan_suami_istri_lang,dengan_sanak_saudara_lang
0,(),(),(),(),()
1,(jawa),(jawa),(jawa),(jawa),(jawa)
2,(),(),(),(),()
3,(),(),(),(),()
4,(),(),(),(),()
...,...,...,...,...,...
457,(madura),(madura),(madura),(madura),(madura)
458,(),(),(),(),()
459,(),(),(),(),()
460,(),(),(jawa),(jawa),(jawa)
461,(jawa),(),(jawa),(jawa),(jawa)

In [14]:
respondent_train_data = shuffled_context_langs.iloc[:462, 90:]
cols = [
    'di_rumah_lang',
    'di_tempat_kerja_lang',
    'dengan_tetangga_lang',
    'dengan_suami_istri_lang',
    'dengan_sanak_saudara_lang'
]
respondent_train_data = respondent_train_data[cols]
respondent_train_data

,di_rumah_lang,di_tempat_kerja_lang,dengan_tetangga_lang,dengan_suami_istri_lang,dengan_sanak_saudara_lang
0,"(indonesia, minang, tebing tinggi)",(),(minang (indomie)),(),"(indonesia, minang, tebing tinggi)"
1,(jawa ngukuh),(indonesia),(jawa ngukuh),(kromo inggil),(kromo inggil)
2,(rote),(),(rote),(),(rote)
3,(ngoko),(),(),(),(ngoko)
4,"(indonesia, minang)","(indonesia, minang)",(minang),(),"(indonesia, minang)"
...,...,...,...,...,...
457,(jawa),(indonesia),(indonesia),(),(indonesia)
458,(indonesia),(),(indonesia),(),(indonesia)
459,(indonesia),(indonesia),(indonesia),(),(indonesia)
460,(indonesia),(),"(indonesia, jawa)",(),"(indonesia, jawa)"
461,(jawa),(indonesia),(jawa halus),(),"(jawa, kromo)"

In [15]:
respondent_validation_data = shuffled_context_langs.iloc[462:561, 90:].reset_index(drop=True)
cols = [
    'di_rumah_lang',
    'di_tempat_kerja_lang',
    'dengan_tetangga_lang',
    'dengan_suami_istri_lang',
    'dengan_sanak_saudara_lang'
]
respondent_validation_data = respondent_validation_data[cols]
respondent_validation_data

,di_rumah_lang,di_tempat_kerja_lang,dengan_tetangga_lang,dengan_suami_istri_lang,dengan_sanak_saudara_lang
0,(jawa),(),(jawa),(),(jawa)
1,(indonesia),(indonesia),(indonesia),(),(indonesia)
2,(indonesia),(),(betawi),(),(indonesia)
3,(kupang),(indonesia),(),(),(kupang)
4,(indonesia),(indonesia),(indonesia),(),(indonesia)
...,...,...,...,...,...
94,(semi formal),(semi formal),(semi formal),(),(semi formal)
95,(jawa ngoko),(jawa kromo),(jawa kromo),(),(jawa kromo)
96,(jawa),(indonesia),(jawa),(),(jawa)
97,(minang),(),"(indonesia, minang)",(),"(indonesia, minang)"
98,"(indonesia, jawa)",(),(jawa),(),"(indonesia, jawa)"

In [16]:
respondent_test_data = shuffled_context_langs.iloc[561:, 90:].reset_index(drop=True)
cols = [
    'di_rumah_lang',
    'di_tempat_kerja_lang',
    'dengan_tetangga_lang',
    'dengan_suami_istri_lang',
    'dengan_sanak_saudara_lang'
]
respondent_test_data = respondent_test_data[cols]
respondent_test_data

,di_rumah_lang,di_tempat_kerja_lang,dengan_tetangga_lang,dengan_suami_istri_lang,dengan_sanak_saudara_lang
0,(jawa),(),(jawa),(),(jawa)
1,(jawa),(),(jawa halus),(),(jawa halus)
2,"(g, pariaman, pa)",(),(pariaman),(),(pariaman)
3,(pak-pak),"(daerah, indonesia)",(pak-pak),(),(pak-pak)
4,(jawa),(),(jawa),(),(jawa)
...,...,...,...,...,...
94,(indonesia),(),(indonesia),(),(indonesia)
95,(),(),(tergantung),(campur),(campur)
96,(indonesia),(),"(indonesia, jawa)",(),(indonesia)
97,(jawa),(),(jawa),(),(jawa)
98,(jawa),"(indonesia, jawa)",(jawa),(jawa),(jawa)

In [17]:
trainer = PerceptronTrainer(ibu_train_data,
                            respondent_train_data,
                            ibu_dari_ibu_train_data,
                            ibu_dari_bapak_train_data)

In [18]:
trainer.load_weights('emits_only9.txt')

In [19]:
trainer.tag_langs(respondent_test_data)

Recorded accuracy: 0.13663194444444446
Recorded precision: 0.6750000000000002
Recorded recall: 0.49021990740740723

In [603]:
trainer.train_to('emits_featsets_in_gparents')

Working on iteration 0...
Finished iteration 0 with 913 incorrect tags and 426 incorrect tag sequences
Working on iteration 1...
Finished iteration 1 with 858 incorrect tags and 414 incorrect tag sequences
Working on iteration 2...
Finished iteration 2 with 815 incorrect tags and 413 incorrect tag sequences
Working on iteration 3...
Finished iteration 3 with 823 incorrect tags and 415 incorrect tag sequences
Working on iteration 4...
Finished iteration 4 with 798 incorrect tags and 411 incorrect tag sequences
Working on iteration 5...
Finished iteration 5 with 788 incorrect tags and 409 incorrect tag sequences
Working on iteration 6...
Finished iteration 6 with 766 incorrect tags and 407 incorrect tag sequences
Working on iteration 7...
Finished iteration 7 with 759 incorrect tags and 405 incorrect tag sequences
Working on iteration 8...
Finished iteration 8 with 753 incorrect tags and 400 incorrect tag sequences
Working on iteration 9...
Finished iteration 9 with 736 incorrect tags and 392 incorrect tag sequences
Working on iteration 10...
Finished iteration 10 with 728 incorrect tags and 403 incorrect tag sequences
Working on iteration 11...
Finished iteration 11 with 730 incorrect tags and 403 incorrect tag sequences
Working on iteration 12...
Finished iteration 12 with 744 incorrect tags and 403 incorrect tag sequences
Working on iteration 13...
Finished iteration 13 with 755 incorrect tags and 399 incorrect tag sequences
Working on iteration 14...
Finished iteration 14 with 715 incorrect tags and 396 incorrect tag sequences
Working on iteration 15...
Finished iteration 15 with 741 incorrect tags and 407 incorrect tag sequences
Working on iteration 16...
Finished iteration 16 with 762 incorrect tags and 407 incorrect tag sequences
Working on iteration 17...
Finished iteration 17 with 726 incorrect tags and 399 incorrect tag sequences
Working on iteration 18...
Finished iteration 18 with 740 incorrect tags and 403 incorrect tag sequences
Working on iteration 19...

KeyboardInterrupt: