# LING 281 Project

## Data Preprocessing

In [45]:
%%bash

head allquestionnaires_section5-7all.csv
#head allquestionnaires_section9.csv

Comments_Page1,Session_token,Person_ID,Year_of_birth,Location_grew_up,Sex,Lived_with_who_when_growing_up,Comments_page5,z_calc_Button_label_locations_list,z_calc_Count_other_people,kinships::z_calc_Beliau_label,kinships::z_calc_Where_label,kinships::z_calc_With_who_label,other_people::Ethnicity,other_people::Kinship_type,other_people::Language_used_at_home_now,other_people::Language_used_at_home_when_young,other_people::Language_used_at_home_at_workplace,other_people::Language_used_at_home_with_neighbours,other_people::Language_used_at_home_with_partner,other_people::Language_used_at_home_with_relatives,other_people::Last_level_of_education,other_people::Location_grewup,other_people::Location_of_home,other_people::Profession,other_people::Religion,other_people::Year_of_birth,other_peoples_languages_FirstLanguage::Language_name,other_peoples_languages_OtherLanguages::Language_name
,IMQYYL,1.30403E+23,1991,Jawa Barat - Kota Depok,Laki,Orang tua,,Pilih lokasi dari propinsi ini saja,8,bahasa / dialek yang dia gunakan...,tempat kerja,dengan pasangannya,,Ibu,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang dia gunakan...,tempat kerja,dengan pasangannya,,Bapak,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang beliau gunakan...,tempat kerja,dengan pasangannya,,Ibu dari ibu,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang beliau gunakan...,tempat kerja,dengan pasangannya,,Bapak dari ibu,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang beliau gunakan...,tempat kerja,dengan pasangannya,,Ibu dari bapak,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang beliau gunakan...,tempat kerja,dengan pasangannya,,Bapak dari bapak,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang dia gunakan...,tempat kerja,dengan orang tua,,Istri/Suami,,,,,,,, , ,,,,,
,,,,,,,,,,bahasa / dialek yang dia gunakan...,tempat kerja/sekolah,dengan orang tua,,Anak Anda,,,,,,,, , ,,,,,
#26 5Mar UI,XHMQVM,1.30404E+23,1993,Banten - Kota Tangerang,Laki,Orang tua,,Pilih lokasi dari propinsi ini saja,8,bahasa / dialek yang dia gunakan...,tempat kerja,dengan pasangannya,Betawi,Ibu,,,,,,,SMA,DKI Jakarta,Banten - Kota Tangerang,ibu rumah tangga,Islam,1953,Bahasa Betawi,Bahasa Indonesia

In [1]:
import pandas as pd

In [46]:
sections1_7 = pd.read_csv('allquestionnaires_section5-7all.csv', dtype=str)
sections1_7 = sections1_7.drop(columns=[
    'Person_ID',
    'Comments_page5',
    'z_calc_Button_label_locations_list',
    'z_calc_Count_other_people',
    'kinships::z_calc_Beliau_label',
    'kinships::z_calc_Where_label',
    'kinships::z_calc_With_who_label',
])

sections1_7.columns = [
    'survey_location',
    'session',
    'birth_year',
    'home_location',
    'sex',
    'caretaker',
    'relative_ethnicity',
    'relative_type',
    'relative_curr_home_lang',
    'relative_past_home_lang',
    'relative_work_lang',
    'relative_neighbor_lang',
    'relative_partner_lang',
    'relative_family_lang',
    'relative_education',
    'relative_past_home',
    'relative_curr_home',
    'relative_profession',
    'relative_religion',
    'relative_birth_year',
    'relative_first_lang',
    'relative_other_langs'
]

sections1_7.head(20)

,survey_location,session,birth_year,home_location,sex,caretaker,relative_ethnicity,relative_type,relative_curr_home_lang,relative_past_home_lang,...,relative_partner_lang,relative_family_lang,relative_education,relative_past_home,relative_curr_home,relative_profession,relative_religion,relative_birth_year,relative_first_lang,relative_other_langs
0,NaN,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN,Ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
8,#26 5Mar UI,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,Betawi,Ibu,NaN,NaN,...,NaN,NaN,SMA,DKI Jakarta,Banten - Kota Tangerang,ibu rumah tangga,Islam,1953,Bahasa Betawi,Bahasa Indonesia
9,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Bapak,NaN,NaN,...,NaN,NaN,sarjana,Jawa Timur,Banten - Kota Tangerang,pegawai swasta,Islam,1957,Bahasa Jawa,Bahasa Indonesia
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
16,#25 5Mar UI,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,Jawa,Ibu,Bahasa Jawa,Bahasa Jawa,...,Bahasa Jawa,Bahasa Jawa,S1,Daerah Istimewa Yogyakarta - Kota Yogyakarta,Jawa Barat - Kota Bekasi,ibu rumah tangga,Kristen (Katolik),1968,Bahasa Indonesia,Bahasa Jawa
17,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Bapak,Bahasa Jawa,Bahasa Jawa,...,Bahasa Jawa,Bahasa Jawa,S1,Jawa Tengah - Kota Surakarta,Jawa Barat - Kota Bekasi,Manager HRD,Kristen (Katolik),1965,Bahasa Indonesia,Bahasa Jawa
18,NaN,NaN,NaN,NaN,NaN,NaN,Jawa,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,Daerah Istimewa Yogyakarta - Kota Yogyakarta,observer,Kristen (Katolik),1951,Bahasa Indonesia,Bahasa Jawa
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,Bahasa Jawa,Bahasa Jawa

In [47]:
section9 = pd.read_csv('allquestionnaires_section9.csv', header=None, dtype=str)
section9.columns = ['survey_location', 'session', 'id', 'birth_year', 'home_location', 'sex', 'visit_frequency']
section9 = section9.drop(columns=['id'])

section9

,survey_location,session,birth_year,home_location,sex,visit_frequency
0,NaN,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,NaN
1,#26 5Mar UI,XHMQVM,1993,Banten - Kota Tangerang,Laki,lebih dari 24
2,#25 5Mar UI,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,12-24
3,#24 5Mar UI,SSXYPN,1993,DKI Jakarta,Laki,lebih dari 24
4,#23 5Mar UI,IGGAXC,1965,DKI Jakarta,Perempuan,1-2
...,...,...,...,...,...,...
655,Tuban-UNIROW-Oktober-2014,VHGHCS,1993,Jawa Timur - Kabupaten Lamongan,Perempuan,1-2
656,Tuban-UNIROW-Oktober-2014,ZFTLQA,1992,Jawa Tengah - Kabupaten Rembang,Perempuan,lebih dari 24
657,Tuban-UNIROW-Oktober-2014,KDYKSR,1986,Jawa Timur - Kabupaten Bojonegoro,Perempuan,lebih dari 24
658,Tuban-UNIROW-Oktober-2014,BJRKZJ,1992,Jawa Timur - Kabupaten Tuban,Perempuan,lebih dari 24
659,Tuban-UNIROW-Oktober-2014,EXAPWK,1992,Jawa Timur - Kabupaten Lamongan,Perempuan,3-5

In [48]:
sections1_9 = sections1_7.merge(section9, how='left')

cols = [
    'survey_location',
    'session',
    'birth_year',
    'home_location',
    'sex',
    'caretaker',
    'visit_frequency',
    'relative_type',
    'relative_curr_home_lang',
    'relative_past_home_lang',
    'relative_work_lang',
    'relative_neighbor_lang',
    'relative_partner_lang',
    'relative_family_lang',
    'relative_ethnicity',
    'relative_education',
    'relative_past_home',
    'relative_curr_home',
    'relative_profession',
    'relative_religion',
    'relative_birth_year',
    'relative_first_lang',
    'relative_other_langs'
]

sections1_9 = sections1_9[cols]

sections1_9.head(20)

,survey_location,session,birth_year,home_location,sex,caretaker,visit_frequency,relative_type,relative_curr_home_lang,relative_past_home_lang,...,relative_family_lang,relative_ethnicity,relative_education,relative_past_home,relative_curr_home,relative_profession,relative_religion,relative_birth_year,relative_first_lang,relative_other_langs
0,NaN,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN,Ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
8,#26 5Mar UI,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,lebih dari 24,Ibu,NaN,NaN,...,NaN,Betawi,SMA,DKI Jakarta,Banten - Kota Tangerang,ibu rumah tangga,Islam,1953,Bahasa Betawi,Bahasa Indonesia
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,NaN,NaN,...,NaN,Jawa,sarjana,Jawa Timur,Banten - Kota Tangerang,pegawai swasta,Islam,1957,Bahasa Jawa,Bahasa Indonesia
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari bapak,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Istri/Suami,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Anak Anda,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,NaN,NaN
16,#25 5Mar UI,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,12-24,Ibu,Bahasa Jawa,Bahasa Jawa,...,Bahasa Jawa,Jawa,S1,Daerah Istimewa Yogyakarta - Kota Yogyakarta,Jawa Barat - Kota Bekasi,ibu rumah tangga,Kristen (Katolik),1968,Bahasa Indonesia,Bahasa Jawa
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak,Bahasa Jawa,Bahasa Jawa,...,Bahasa Jawa,Jawa,S1,Jawa Tengah - Kota Surakarta,Jawa Barat - Kota Bekasi,Manager HRD,Kristen (Katolik),1965,Bahasa Indonesia,Bahasa Jawa
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ibu dari ibu,NaN,NaN,...,NaN,Jawa,NaN,,Daerah Istimewa Yogyakarta - Kota Yogyakarta,observer,Kristen (Katolik),1951,Bahasa Indonesia,Bahasa Jawa
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Bapak dari ibu,NaN,NaN,...,NaN,NaN,NaN,,,NaN,NaN,NaN,Bahasa Jawa,Bahasa Jawa

In [31]:
sections1_9.to_csv('allquestionnaires_sections1-9.csv', index=False)

In [49]:
sections1_9 = sections1_9.iloc[:, 1:7]
sections1_9.head(20)

,session,birth_year,home_location,sex,caretaker,visit_frequency
0,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN
8,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,lebih dari 24
9,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN
16,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,12-24
17,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
sections1_9 = sections1_9.loc[sections1_9['session'].notnull()]
sections1_9

,session,birth_year,home_location,sex,caretaker,visit_frequency
0,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN
8,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,lebih dari 24
16,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,12-24
24,SSXYPN,1993,DKI Jakarta,Laki,Keluarga,lebih dari 24
32,IGGAXC,1965,DKI Jakarta,Perempuan,Orang tua,1-2
...,...,...,...,...,...,...
5256,VHGHCS,1993,Jawa Timur - Kabupaten Lamongan,Perempuan,Orangtua,1-2
5264,ZFTLQA,1992,Jawa Tengah - Kabupaten Rembang,Perempuan,Orangtua,lebih dari 24
5272,KDYKSR,1986,Jawa Timur - Kabupaten Bojonegoro,Perempuan,Orangtua,lebih dari 24
5280,BJRKZJ,1992,Jawa Timur - Kabupaten Tuban,Perempuan,Orangtua,lebih dari 24
5288,EXAPWK,1992,Jawa Timur - Kabupaten Lamongan,Perempuan,Wiraswasta,3-5

In [43]:
sections1_9.to_csv('allquestionnaires_sections1-9_abridged.csv', index=False)

In [61]:
usage = pd.read_csv('Usage.csv', header=None, dtype=str)
usage.head(40)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,NaN,IMQYYL,1.30403E+23,1991,Jawa Barat - Kota Depok,Laki,Indonesia,Sangat lancar,Sangat lancar,Sangat lancar,Lancar,dengan ibu,Indonesia
1,NaN,NaN,NaN,NaN,NaN,NaN,Inggris,Lancar,Lancar,Lancar,Lancar,dengan bapak,Indonesia
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan kakak/adik,Indonesia
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan nenek dan kakek,Indonesia
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan suami/istri (kalau sudah menikah),NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"dengan sanak saudara (tante, om, sepupu, dll)",Indonesia
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan tetangga,Indonesia
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan pembantu,Indonesia
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,apabila marah,Inggris
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dalam mimpi,Inggris
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,berhitung,Indonesia
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kirim sms ke keluarga,Indonesia
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kirim sms ke teman,Inggris
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,kirim sms ke suami/istri,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dalam jejaring sosial (FB),Inggris
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,berdoa dalam hati,Indonesia
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,berdoa di tempat ibadah,Indonesia
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di rumah,Indonesia
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di tempat kerja,Inggris
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di pasar,Indonesia
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di warung,Indonesia
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di bank,Indonesia
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di kantor pos,Indonesia
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di SD dengan guru,Indonesia
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di SD dengan teman sekelas,Indonesia
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di SMA dengan guru,Indonesia
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di SMA dengan teman sekelas,Indonesia
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,di kendaraan umum,Indonesia
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca novel/buku cerita,Indonesia
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca koran,Inggris
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca majalah,Inggris
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mendengar musik,Inggris
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mendengar radio,Indonesia
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,menonton TV,Indonesia
34,#26 5Mar UI,XHMQVM,1.30404E+23,1993,Banten - Kota Tangerang,Laki,Bahasa Indonesia,Sangat lancar,Sangat lancar,Sangat lancar,Sangat lancar,dengan ibu,"Bahasa Indonesia, Bahasa Betawi"
35,NaN,NaN,NaN,NaN,NaN,NaN,Bahasa Betawi,Lancar,Lancar,Lancar,Agak lancar,dengan bapak,Bahasa Indonesia
36,NaN,NaN,NaN,NaN,NaN,NaN,Bahasa Sunda,Sedikit lancar,Sedikit lancar,Sedikit lancar,Tidak bisa,dengan kakak/adik,Bahasa Indonesia
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan nenek dan kakek,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan suami/istri (kalau sudah menikah),NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"dengan sanak saudara (tante, om, sepupu, dll)",Bahasa Indonesia

In [62]:
usage.columns = [
    'survey_location',
    'session',
    'id',
    'birth_year',
    'home_location',
    'sex',
    'prof_lang',
    'prof_understand',
    'prof_speak',
    'prof_read',
    'prof_write',
    'domain',
    'domain_lang'
]

usage

,survey_location,session,id,birth_year,home_location,sex,prof_lang,prof_understand,prof_speak,prof_read,prof_write,domain,domain_lang
0,NaN,IMQYYL,1.30403E+23,1991,Jawa Barat - Kota Depok,Laki,Indonesia,Sangat lancar,Sangat lancar,Sangat lancar,Lancar,dengan ibu,Indonesia
1,NaN,NaN,NaN,NaN,NaN,NaN,Inggris,Lancar,Lancar,Lancar,Lancar,dengan bapak,Indonesia
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan kakak/adik,Indonesia
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan nenek dan kakek,Indonesia
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,dengan suami/istri (kalau sudah menikah),NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
22435,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca koran,Indonesia
22436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,membaca majalah,Indonesia
22437,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mendengar musik,"Indonesia, India, Inggris, Korea"
22438,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mendengar radio,Indonesia
22439,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,menonton TV,"Indonesia, India, Inggris, Korea"

In [63]:
usage = usage.drop(columns=[
    'survey_location',
    'id',
    'prof_lang',
    'prof_understand',
    'prof_speak',
    'prof_read',
    'prof_write'
])

usage

,session,birth_year,home_location,sex,domain,domain_lang
0,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,dengan ibu,Indonesia
1,NaN,NaN,NaN,NaN,dengan bapak,Indonesia
2,NaN,NaN,NaN,NaN,dengan kakak/adik,Indonesia
3,NaN,NaN,NaN,NaN,dengan nenek dan kakek,Indonesia
4,NaN,NaN,NaN,NaN,dengan suami/istri (kalau sudah menikah),NaN
...,...,...,...,...,...,...
22435,NaN,NaN,NaN,NaN,membaca koran,Indonesia
22436,NaN,NaN,NaN,NaN,membaca majalah,Indonesia
22437,NaN,NaN,NaN,NaN,mendengar musik,"Indonesia, India, Inggris, Korea"
22438,NaN,NaN,NaN,NaN,mendengar radio,Indonesia
22439,NaN,NaN,NaN,NaN,menonton TV,"Indonesia, India, Inggris, Korea"

In [65]:
usage.to_csv('usage_abridged.csv', index=False)

In [5]:
usages_unpacked = pd.read_csv('allquestionnaires_sections1-9_unpacked_usages.csv', dtype=str)
usages_unpacked

,session,birth_year,home_location,sex,caretaker,visit_frequency,ibu_curr_home_lang,ibu_past_home_lang,ibu_work_lang,ibu_neighbor_lang,...,di_sd_dengan_teman_sekelas_lang,di_sma_dengan_guru_lang,di_sma_dengan_teman_sekelas_lang,di_kendaraan_umum_lang,membaca_novel_lang,membaca_koran_lang,membaca_majalah_lang,mendengar_musik_lang,mendengar_radio_lang,menonton_tv_lang
0,IMQYYL,1991,Jawa Barat - Kota Depok,Laki,Orang tua,NaN,NaN,NaN,NaN,NaN,...,Indonesia,Indonesia,Indonesia,Indonesia,Indonesia,Inggris,Inggris,Inggris,Indonesia,Indonesia
1,XHMQVM,1993,Banten - Kota Tangerang,Laki,Orang tua,lebih dari 24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Bahasa Indonesia,NaN,NaN,Bahasa Inggris,NaN,NaN
2,OQHPQE,1995,Jawa Timur - Kota Surabaya,Perempuan,Orang tua,12-24,Bahasa Jawa,Bahasa Jawa,Bahasa Indonesia,Bahasa Indonesia,...,"Bahasa Indonesia, Bahasa Jawa",Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,"Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris",Bahasa Indonesia,"Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris"
3,SSXYPN,1993,DKI Jakarta,Laki,Keluarga,lebih dari 24,"Bahasa Indonesia, Bahasa Minang",Bahasa Minang,Bahasa Indonesia,Bahasa Indonesia,...,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia
4,IGGAXC,1965,DKI Jakarta,Perempuan,Orang tua,1-2,"Bahasa Indonesia, Bahasa Sunda",Bahasa Sunda,Bahasa Indonesia,Bahasa Indonesia,...,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,Bahasa Indonesia,"Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris","Bahasa Indonesia, Bahasa Inggris"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,VHGHCS,1993,Jawa Timur - Kabupaten Lamongan,Perempuan,Orangtua,1-2,Jawa,Jawa,NaN,Jawa,...,Jawa,"Indonesia, Jawa","Indonesia, Jawa",Jawa,"Inggris, Indonesia, Jawa","Indonesia, Inggris",Indonesia,"Indonesia, Inggris",Indonesia,"Indonesia, Jawa"
656,ZFTLQA,1992,Jawa Tengah - Kabupaten Rembang,Perempuan,Orangtua,lebih dari 24,Jawa,Jawa,NaN,Jawa,...,"Jawa, Indonesia",Indonesia,"Jawa, Indonesia",Indonesia,"Indonesia, Inggris",Indonesia,Indonesia,"Indonesia, Inggris",Indonesia,Indonesia
657,KDYKSR,1986,Jawa Timur - Kabupaten Bojonegoro,Perempuan,Orangtua,lebih dari 24,Jawa,Jawa,NaN,Jawa,...,"Jawa, Indonesia",Indonesia,"Jawa, Indonesia",Jawa,"Indonesia, Inggris","Indonesia, Inggris","Indonesia, Inggris","Indonesia, Inggris",Indonesia,"Indonesia, Inggris"
658,BJRKZJ,1992,Jawa Timur - Kabupaten Tuban,Perempuan,Orangtua,lebih dari 24,"Jawa, Indonesia",Jawa,"Jawa, Indonesia",Jawa,...,"Jawa, Indonesia",Indonesia,"Jawa, Indonesia",Indonesia,"Indonesia, Inggris",Indonesia,Indonesia,"Indonesia, Inggris",Indonesia,"Indonesia, Inggris"
659,EXAPWK,1992,Jawa Timur - Kabupaten Lamongan,Perempuan,Wiraswasta,3-5,Jawa,"Jawa, Indonesia",NaN,Jawa,...,Jawa,Indonesia,"Jawa, Indonesia",Jawa,Indonesia,Indonesia,Indonesia,"Indonesia, India, Inggris, Korea",Indonesia,"Indonesia, India, Inggris, Korea"

In [6]:
usages_unpacked = usages_unpacked.applymap(lambda x: x if pd.isna(x) else x.lower())
usages_unpacked

,session,birth_year,home_location,sex,caretaker,visit_frequency,ibu_curr_home_lang,ibu_past_home_lang,ibu_work_lang,ibu_neighbor_lang,...,di_sd_dengan_teman_sekelas_lang,di_sma_dengan_guru_lang,di_sma_dengan_teman_sekelas_lang,di_kendaraan_umum_lang,membaca_novel_lang,membaca_koran_lang,membaca_majalah_lang,mendengar_musik_lang,mendengar_radio_lang,menonton_tv_lang
0,imqyyl,1991,jawa barat - kota depok,laki,orang tua,NaN,NaN,NaN,NaN,NaN,...,indonesia,indonesia,indonesia,indonesia,indonesia,inggris,inggris,inggris,indonesia,indonesia
1,xhmqvm,1993,banten - kota tangerang,laki,orang tua,lebih dari 24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,bahasa indonesia,NaN,NaN,bahasa inggris,NaN,NaN
2,oqhpqe,1995,jawa timur - kota surabaya,perempuan,orang tua,12-24,bahasa jawa,bahasa jawa,bahasa indonesia,bahasa indonesia,...,"bahasa indonesia, bahasa jawa",bahasa indonesia,bahasa indonesia,bahasa indonesia,"bahasa indonesia, bahasa inggris","bahasa indonesia, bahasa inggris",bahasa indonesia,"bahasa indonesia, bahasa inggris","bahasa indonesia, bahasa inggris","bahasa indonesia, bahasa inggris"
3,ssxypn,1993,dki jakarta,laki,keluarga,lebih dari 24,"bahasa indonesia, bahasa minang",bahasa minang,bahasa indonesia,bahasa indonesia,...,bahasa indonesia,bahasa indonesia,bahasa indonesia,bahasa indonesia,bahasa indonesia,bahasa indonesia,bahasa indonesia,bahasa indonesia,bahasa indonesia,bahasa indonesia
4,iggaxc,1965,dki jakarta,perempuan,orang tua,1-2,"bahasa indonesia, bahasa sunda",bahasa sunda,bahasa indonesia,bahasa indonesia,...,bahasa indonesia,bahasa indonesia,bahasa indonesia,bahasa indonesia,"bahasa indonesia, bahasa inggris","bahasa indonesia, bahasa inggris","bahasa indonesia, bahasa inggris","bahasa indonesia, bahasa inggris","bahasa indonesia, bahasa inggris","bahasa indonesia, bahasa inggris"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,vhghcs,1993,jawa timur - kabupaten lamongan,perempuan,orangtua,1-2,jawa,jawa,NaN,jawa,...,jawa,"indonesia, jawa","indonesia, jawa",jawa,"inggris, indonesia, jawa","indonesia, inggris",indonesia,"indonesia, inggris",indonesia,"indonesia, jawa"
656,zftlqa,1992,jawa tengah - kabupaten rembang,perempuan,orangtua,lebih dari 24,jawa,jawa,NaN,jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",indonesia,"indonesia, inggris",indonesia,indonesia,"indonesia, inggris",indonesia,indonesia
657,kdyksr,1986,jawa timur - kabupaten bojonegoro,perempuan,orangtua,lebih dari 24,jawa,jawa,NaN,jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",jawa,"indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris",indonesia,"indonesia, inggris"
658,bjrkzj,1992,jawa timur - kabupaten tuban,perempuan,orangtua,lebih dari 24,"jawa, indonesia",jawa,"jawa, indonesia",jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",indonesia,"indonesia, inggris",indonesia,indonesia,"indonesia, inggris",indonesia,"indonesia, inggris"
659,exapwk,1992,jawa timur - kabupaten lamongan,perempuan,wiraswasta,3-5,jawa,"jawa, indonesia",NaN,jawa,...,jawa,indonesia,"jawa, indonesia",jawa,indonesia,indonesia,indonesia,"indonesia, india, inggris, korea",indonesia,"indonesia, india, inggris, korea"

In [77]:
usages_unpacked.to_csv('usages_unpacked_lowered.csv', index=False)

In [7]:
import re

usages_unpacked = usages_unpacked.applymap(lambda x: x if pd.isna(x) else re.sub('bahasa ', '', x))
usages_unpacked

,session,birth_year,home_location,sex,caretaker,visit_frequency,ibu_curr_home_lang,ibu_past_home_lang,ibu_work_lang,ibu_neighbor_lang,...,di_sd_dengan_teman_sekelas_lang,di_sma_dengan_guru_lang,di_sma_dengan_teman_sekelas_lang,di_kendaraan_umum_lang,membaca_novel_lang,membaca_koran_lang,membaca_majalah_lang,mendengar_musik_lang,mendengar_radio_lang,menonton_tv_lang
0,imqyyl,1991,jawa barat - kota depok,laki,orang tua,NaN,NaN,NaN,NaN,NaN,...,indonesia,indonesia,indonesia,indonesia,indonesia,inggris,inggris,inggris,indonesia,indonesia
1,xhmqvm,1993,banten - kota tangerang,laki,orang tua,lebih dari 24,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,indonesia,NaN,NaN,inggris,NaN,NaN
2,oqhpqe,1995,jawa timur - kota surabaya,perempuan,orang tua,12-24,jawa,jawa,indonesia,indonesia,...,"indonesia, jawa",indonesia,indonesia,indonesia,"indonesia, inggris","indonesia, inggris",indonesia,"indonesia, inggris","indonesia, inggris","indonesia, inggris"
3,ssxypn,1993,dki jakarta,laki,keluarga,lebih dari 24,"indonesia, minang",minang,indonesia,indonesia,...,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia,indonesia
4,iggaxc,1965,dki jakarta,perempuan,orang tua,1-2,"indonesia, sunda",sunda,indonesia,indonesia,...,indonesia,indonesia,indonesia,indonesia,"indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
655,vhghcs,1993,jawa timur - kabupaten lamongan,perempuan,orangtua,1-2,jawa,jawa,NaN,jawa,...,jawa,"indonesia, jawa","indonesia, jawa",jawa,"inggris, indonesia, jawa","indonesia, inggris",indonesia,"indonesia, inggris",indonesia,"indonesia, jawa"
656,zftlqa,1992,jawa tengah - kabupaten rembang,perempuan,orangtua,lebih dari 24,jawa,jawa,NaN,jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",indonesia,"indonesia, inggris",indonesia,indonesia,"indonesia, inggris",indonesia,indonesia
657,kdyksr,1986,jawa timur - kabupaten bojonegoro,perempuan,orangtua,lebih dari 24,jawa,jawa,NaN,jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",jawa,"indonesia, inggris","indonesia, inggris","indonesia, inggris","indonesia, inggris",indonesia,"indonesia, inggris"
658,bjrkzj,1992,jawa timur - kabupaten tuban,perempuan,orangtua,lebih dari 24,"jawa, indonesia",jawa,"jawa, indonesia",jawa,...,"jawa, indonesia",indonesia,"jawa, indonesia",indonesia,"indonesia, inggris",indonesia,indonesia,"indonesia, inggris",indonesia,"indonesia, inggris"
659,exapwk,1992,jawa timur - kabupaten lamongan,perempuan,wiraswasta,3-5,jawa,"jawa, indonesia",NaN,jawa,...,jawa,indonesia,"jawa, indonesia",jawa,indonesia,indonesia,indonesia,"indonesia, india, inggris, korea",indonesia,"indonesia, india, inggris, korea"

In [8]:
usages_unpacked.to_csv('usages_unpacked_lowered_trimmed.csv', index=False)